const data={
    products: [
        {
        _id: '1',
        name:'Cheese Burgur',
        category:'kfc',
        image:'/images/cheeseburgur.jpg',
        price: 120,
        brand: 'Burgur',
        rating: 4.5,
        numReviews:10,
        description: 'High quality product',
        },
        {
            _id: '2',
            name:'Cheese Pizza',
            category:'mcdonald',
            image:'/images/cheesepizza.jpg',
            price: 100,
            brand: 'pizza',
            rating: 4,
            numReviews:10,
            description: 'High quality product',
            },
            {
                _id: '3',
                name:'Chicken Nuggets',
                category:'kfc',
                image:'/images/chickennuggets.jpg',
                price: 120,
                brand: 'Nuggets',
                rating: 5.5,
                numReviews:10,
                description: 'High quality product',
                },
                {
                    _id: '4',
                    name:'Chicken Wings',
                    category:'kfc',
                    image:'/images/chickenwings.jpg',
                    price: 90,
                    brand: 'Wings',
                    rating: 5,
                    numReviews:10,
                    description: 'High quality product',
                    },
                    {
                        _id: '5',
                        name:'Plate Zwarma',
                        category:'mcdonald',
                        image:'/images/platezwarma.jpg',
                        price: 150,
                        brand: 'Zwarma',
                        rating: 6,
                        numReviews:10,
                        description: 'High quality product',
                        },
                        {
                            _id: '6',
                            name:'Crispy',
                            category:'kfc',
                            image:'/images/crispy.jpg',
                            price: 100,
                            brand: 'Chicken',
                            rating: 8,
                            numReviews:10,
                            description: 'High quality product',
                            },
                            {
                                _id: '7',
                                name:'Double Cheese Burgur',
                                category:'kfc',
                                image:'/images/doublecheeseburgur.jpg',
                                price: 220,
                                brand: 'Burgur',
                                rating: 4.5,
                                numReviews:10,
                                description: 'High quality product',
                                },
                                {
                                    _id: '8',
                                    name:'Fried Chicken',
                                    category:'kfc',
                                    image:'/images/friedchicken.jpg',
                                    price: 200,
                                    brand: 'Chicken',
                                    rating: 7.5,
                                    numReviews:10,
                                    description: 'High quality product',
                                    },

    ],
};
export default data;